export function createAppState({
  readCommandHistory = () => [],
  defaultGamepadSettings = () => ({}),
  defaultMachineSettings = () => ({}),
  defaultDashboardSettings = () => ({}),
  loadSurfaceViewPreferences = () => ({}),
  defaultOutlineState = () => ({}),
  defaultWorkAreaView = () => ({}),
  activeJobSplitDefaultPercent = 32,
} = {}) {
  return {
    readOnly: false,
    machine: { state: "", mode: "owner", age_ms: 0, connected: false },
    gcodeSeqs: new Set(),
    gcodeLines: [],
    commandHistory: readCommandHistory(),
    historyIndex: -1,
    logFilter: "all",
    logSearch: "",
    logPaused: false,
    selectedMacroId: "",
    ui: { macros: [], macro_buttons: [], log: { filter: "all", autoscroll: true }, gamepad: defaultGamepadSettings(), machine: defaultMachineSettings(), dashboard: defaultDashboardSettings() },
    settingsSaveTimer: null,
    machineLearnPending: false,
    macroRunning: false,
    activeTab: "active-job",
    surface: loadSurfaceViewPreferences(),
    activeJobLeftTab: "source",
    activeJobSplitPercent: activeJobSplitDefaultPercent,
    dashboardProfileID: "overview",
    dashboardRequestedProfileID: "",
    dashboardEmbed: false,
    dashboardSettingsLoaded: false,
    dashboardDraftProfileID: "",
    controlPendingAction: "",
    gcodePending: false,
    autoVacuumPending: false,
    lastControlResult: null,
    activeGcode: { path: "", runnable: false, message: "" },
    externalJobObservedAt: 0,
    activeGcodePending: "",
    feedOverridePendingPercent: null,
    activeGcodeLoading: false,
    activeSelectPendingPath: "",
    toolPending: "",
    gamepadMacroBindingDirty: false,
    jog: {
      caps: null,
      ws: null,
      seq: 1,
      armed: false,
      link: "offline",
      pad: "",
      deadman: false,
      axes: { x: 0, y: 0, z: 0, a: 0 },
      mpos: null,
      wpos: null,
      observed: null,
      estimated: false,
      estimatedUntil: 0,
      statusRevision: 0,
      motionRevision: 0,
      settledMotionRevision: 0,
      motionRevisionKnown: false,
      motionStreamRevision: 0,
      availability: null,
      target: null,
      lead: { x: 0, y: 0, z: 0, a: 0 },
      path: [],
      buttons: [],
      armPending: 0,
      armPendingAction: "",
      armQueuedAction: "",
      disarmAfterPendingArm: false,
      targetPending: 0,
      targetMotionPending: 0,
      fieldProbeMovePending: 0,
      workMovePending: 0,
      targetLabel: "",
      zStepPending: 0,
      zStepLabel: "",
      surfaceStepPending: 0,
      surfaceStepSource: "",
      commandDisarm: null,
      zProbePending: false,
      probe3DPending: false,
      originPending: 0,
      originPendingAxis: "",
      originPendingMode: "",
      originPendingAxes: [],
      originPendingIndex: 0,
      originPendingTargets: null,
      originPendingLabel: "",
      originVerifyDeadline: 0,
      originVerifyTimer: null,
      tapFeedback: "",
      tapFeedbackKind: "",
      error: "",
      errorCode: "",
      sent: new Map(),
      reconnectTimer: null,
      reconnectAttempt: 0,
      sampleTimer: null,
      preferredPadIndex: null,
      lastInput: null,
      lastInputSentAt: 0,
      inputSuspended: false,
      surfaceInput: null,
      surfaceWheel: { pointerId: null, lastAngle: null, angle: 0, remainder: 0, value: 0, gestureSteps: 0, gestureAccepted: 0, gestureReleased: false, gestureAxis: "", blocked: false },
      outlineCaptureIntents: [],
    },
    outline: defaultOutlineState(),
    workarea: defaultWorkAreaView(),
  };
}
